#!/bin/bash
shopt -q expand_aliases||{ unalias -a;shopt -s expand_aliases;};builtin alias\
	+='{ ::__;::(){ ((!$#))||{ shift;"${__dsl__[@]-::no-dsl}" '\
	~='{ ::__;::(){ ((!$#))||{ shift; ' -='"${__dsl__[@]-::no-dsl}" '\
	'{{=return;return;};__blk__=;set -- "${__blarg__[@]:1}"; ' '}}=};__:: 0 "$@";}'
eval $'::block(){ ((!$#))||local __dsl__=("$@");${__blk__:+::};};__bsp__=
::__(){ __bsp__=("${__blk__:+__blk__=1;$(declare -f ::);}" "${__bsp__[@]}");}
__::(){ local __blarg__=("$@");__blk__=1;:: "$@"||set -- $?;__blk__=;local REPLY;eval \'__bsp__=("${__bsp__[@]:1}");\'"$__bsp__"||:;return $1;}'
