#!/bin/bash
shopt -q expand_aliases||{ unalias -a;shopt -s expand_aliases;};builtin alias\
	+='{ ::__;::(){ ((!$#))||{ shift;"${__dsl__[@]-::no-dsl}" '\
	~='{ ::__;::(){ ((!$#))||{ shift; ' -='"${__dsl__[@]-::no-dsl}" '\
	'{{=return;return;};__blk__=;set -- "${__blarg__[@]:1}"; ' '}}=};__:: 0 "$@";}'
eval 'dsl:(){ ((!$#))||local __dsl__=("$@");${__blk__:+::};};__bsp__=0
::__(){ __bstk__[__bsp__++]="${__blk__:+__blk__=1;$(declare -f ::)}";}
__::(){ local __blarg__=("$@");__blk__=1;:: "$@"||set -- $?;__blk__=;local REPLY;${__bstk__[--__bsp__]:+eval "${__bstk__[__bsp__]}"}||:;return $1;}'
